a = input('Digite algo:')

print('O tipo primitivo desse valor é:', type(a))
# print('Só tem espaços?', a.isspace())
print('{} só tem espaços?' .format(a), a.isspace())
# print('É número?', a.isnumeric())
print('{} é um número?' .format(a), a.isalnum())
# print('É alfabético ?', a.isalpha())
print('{} é alfabético?' .format(a), a.isalpha())
# print('É maíusculo?', a.isupper())
print('{} é maiúsculo?' .format(a), a.isupper())
# print('É minúsculo?', a.islower())
print('{} é minúsculo?' .format(a), a.islower())
# print('Está capitalizado?', a.istitle())
print('{} está capitalizado?' .format(a), a.istitle())
# print('É alfanumérico?', a.isalnum())
print('{} é alfanumérico?' .format(a), a.isalnum())